music-managment/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, Song, LikedSongs
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user
from datetime import datetime

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if user.password == password:
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist. Sign up to create a new account.', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/manage', methods=['GET', 'POST'])
@login_required
def manage():
    if request.method == 'POST': 
        song = request.form.get('title') 
        release = request.form.get('release_date') 
        release = datetime.strptime(release, '%Y-%m-%d').date()
        new_song = Song(title=song, artist_id=current_user.id, release_date=release)
        db.session.add(new_song)
        db.session.commit()
        flash('Song added!', category='success')

    all_songs = Song.query.all()
    liked_songs = [song.song_id for song in LikedSongs.query.filter_by(user_id=current_user.id).all()] 

    return render_template("profile.html", user=current_user, songs=all_songs, liked_songs=liked_songs)


@auth.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    all_songs = Song.query.all()
    liked_songs = [song.song_id for song in LikedSongs.query.filter_by(user_id=current_user.id).all()] 
    if request.method == 'POST':
        search_query = request.form.get('search_query')
        if search_query:
            search_results = Song.query.filter(
                (Song.title.ilike(f"%{search_query}%")) |
                (Song.artist.has(User.name.ilike(f"%{search_query}%")))
            ).all()
            return render_template("search.html", user=current_user, search_results=search_results, songs=all_songs, liked_songs=liked_songs)

    return render_template("search.html", user=current_user, search_results=None, songs=all_songs, liked_songs=liked_songs)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        name = request.form.get('name')
        dob_str = request.form.get('dateOfBirth')
        artist = request.form.get('isArtist')
        password1 = request.form.get('password1')
        confirmPassword = request.form.get('confirmPassword')

        dob = datetime.strptime(dob_str, '%Y-%m-%d').date()
        is_artist = bool(int(artist))

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != confirmPassword:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, name=name, password=password1, date_of_birth=dob, is_artist=is_artist)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

music-managment/website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, session
from flask_login import login_required, current_user
from .models import Song, LikedSongs
from . import db
import json
from datetime import datetime
from flask import redirect, url_for

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST': 
        song = request.form.get('title') 
        release = request.form.get('release_date') 
        release = datetime.strptime(release, '%Y-%m-%d').date()
        new_song = Song(title=song, artist_id=current_user.id, release_date=release)
        db.session.add(new_song)
        db.session.commit()
        flash('Song added!', category='success')
        return redirect(url_for('views.home'))

    # Query all songs from the database
    all_songs = Song.query.all()
    liked_songs = [song.song_id for song in LikedSongs.query.filter_by(user_id=current_user.id).all()] 

    return render_template("home.html", user=current_user, songs=all_songs, liked_songs=liked_songs)



@views.route('/guest', methods=['GET'])
def guest():
    all_songs = Song.query.all()
    return render_template("guest.html", songs=all_songs, user=None)



@views.route('/delete-song', methods=['POST'])
def delete_song():
    data = json.loads(request.data)
    song_id = data['songId']
    song = Song.query.get(song_id)
    if song:
        if song.artist_id == current_user.id:
            db.session.delete(song)
            db.session.commit()
            flash('Song deleted!', category='danger')
        else:
            flash('song.artist_id != current_user.id!', category='danger')
    else:
        flash('No song!', category='danger')

    return jsonify({})


@views.route('/like/<int:song_id>', methods=['POST'])
@login_required
def like_song(song_id):
    song = Song.query.get(song_id)
    if song:
        already_liked = LikedSongs.query.filter_by(user_id=current_user.id, song_id=song_id).first()
        if not already_liked:
            new_liked_song = LikedSongs(user_id=current_user.id, song_id=song_id)
            db.session.add(new_liked_song)
            db.session.commit()
    
    # Store the referrer URL in session
    session['referrer'] = request.referrer
    
    # Redirect to the referrer URL
    return redirect(session.get('referrer', url_for('views.home')))

@views.route('/unlike/<int:song_id>', methods=['POST'])
@login_required
def unlike_song(song_id):
    song = Song.query.get(song_id)
    if song:
        liked_song = LikedSongs.query.filter_by(user_id=current_user.id, song_id=song_id).first()
        if liked_song:
            db.session.delete(liked_song)
            db.session.commit()
    
    # Store the referrer URL in session
    session['referrer'] = request.referrer
    
    # Redirect to the referrer URL
    return redirect(session.get('referrer', url_for('views.home')))

music-managment/website/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous" />

  <link rel="icon" type="image/x-icon" href="/logo.ico">

  <title>{% block title %}Home{% endblock %}</title>

  <style>
    .navbar {
      position: fixed;
      top: 0;
      bottom: 0;
      left: 0;
      width: 250px;
      background-color: #343a40;
      padding-top: 2rem;
      display: flex;
      flex-direction: column;
      justify-content: start;
      align-items: flex-start;
    }

    .navbar-brand {
      font-size: 2rem;
      margin-right: 2rem;
      font-weight: bold;
      color: #fff;
    }

    .navbar-nav {
      margin-bottom: 1rem;
    }

    .liked-song {
      color: #a2a2a2;
      padding: 0;
      margin: 0;
    }

    .liked-song:hover {
      color: #a2a2a2;
      text-decoration: underline;
      cursor: pointer;
    }

    .nav-link {
      color: #a2a2a2;
    }

    .content {
      margin-left: 250px;
      padding: 2rem;
    }
  </style>
</head>

<body>
  <nav class="navbar">
    <a class="navbar-brand" href="/">Mingo Bingo</a>
    <div style="width: 100%;">
      {% if user.is_authenticated %}
      <ul class="navbar-nav">
        <li>
          <a class="nav-link" id="home" href="/">Home</a>
        </li>
        <li>
          <a class="nav-link" id="manage" href="/manage">Profile</a>
        </li>
        <li>
          <a class="nav-link" id="search" href="/search">search</a>
        </li>
        <li>
          <a class="nav-link" id="logout" href="#" onclick="confirmLogout()">Logout</a>
        </li>
      </ul>
      <h4 style="color: #d4d4d4;">Liked Songs</h4>
      <ul class="navbar-nav">
        {% for song in songs %}
        {% if song.id in liked_songs %}
        <li>
          <p class="liked-song" onclick="confirmUnlike('{{ song.id }}')" >{{ song.title }}</p>
        </li>
        {% endif %}
        {% endfor %}
      </ul>
      
      {% else %}
      <ul class="navbar-nav">
        <li>
          <a class="liked-song" id="manage" href="/guest">Continue as guest</a>
        </li>
        <li>
          <a class="liked-song" id="home" href="/login">Login in</a>
        </li>
        <li>
          <a class="liked-song" id="manage" href="/sign-up">Join</a>
        </li>
      </ul>
      {% endif %}
    </div>
  </nav>

  <!-- Main content -->
  <div class="content">
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">
      {% block content %} {% endblock %}
    </div>
  </div>

  <dialog id="unlikeConfirmation">
    <p>Are you sure you want to unlike this song?</p>
    <button id="confirmUnlikeButton">Yes</button>
    <button id="cancelUnlikeButton">No</button>
  </dialog>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block javascript %}
  <script type="text/javascript">
    function confirmLogout() {
      const dialog = document.getElementById('logoutConfirmation');
      dialog.showModal();
    }

    function logout() {
      window.location.href = "/logout";
    }

    function confirmUnlike(songId) {
        const dialog = document.getElementById('unlikeConfirmation');
        dialog.showModal();

        const confirmButton = document.getElementById('confirmUnlikeButton');
        const cancelButton = document.getElementById('cancelUnlikeButton');

        confirmButton.onclick = function () {
          unlikeSong(songId);
          dialog.close();
        };

        cancelButton.onclick = function () {
          dialog.close();
        };
      }

      function unlikeSong(songId) {
        fetch("/unlike/" + songId, {
          method: "POST",
          body: JSON.stringify({ songId: songId }),
        }).then(window.location.reload());
      }

  </script>
  {% endblock %}
</body>

<!-- Confirmation Dialog for Logout -->
<dialog id="logoutConfirmation">
  <p>Are you sure you want to log out?</p>
  <button onclick="logout()">Yes</button>
  <button onclick="document.getElementById('logoutConfirmation').close()">No</button>
</dialog>

</html>

music-managment/website/templates/guest.html
{% extends "base.html" %}
{% block title %}Guest{% endblock %}
{% block content %}

<div class="container">
    <h3 align="center">All Songs</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Release Date</th>
                <th>Artist</th>
            </tr>
        </thead>
        <tbody>
            {% for song in songs %}
            <tr>
                <td>{{ song.title }}</td>
                <td>{{ song.release_date }}</td>
                <td>{{ song.artist.name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

music-managment/website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

{% if user.is_artist %}
{% if user.songs %}
<h3 align="center">My Songs</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Release Date</th>
    </tr>
  </thead>
  <tbody>
    {% for song in user.songs %}
    <tr>
      <td>{{ song.title }}</td>
      <td>{{ song.release_date }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<hr>
{% endif %}
{% endif %}

<h3 align="center">All Songs</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Release Date</th>
      <th>Artist</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    {% for song in songs %}
    <tr>
      <td>{{ song.title }}</td>
      <td>{{ song.release_date }}</td>
      <td>{{ song.artist.name }}</td>
      <td>
        {% if song.id in liked_songs %}
        <form action="{{ url_for('views.unlike_song', song_id=song.id) }}" method="post">
          <button type="submit" class="btn btn-danger"><i class="fa fa-heart"></i></button>
        </form>
        {% else %}
        <form action="{{ url_for('views.like_song', song_id=song.id) }}" method="post">
          <button type="submit" class="btn btn-primary"><i class="fa fa-heart"></i></button>
        </form>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

music-managment/website/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center vh-100">
  <div class="row justify-content-center w-full">
    <div style="min-width: 30em;">
      <form method="POST">
        <h3 class="text-center">Welcome to Mingo Bingo</h3>
        <p class="text-center">Please sign in to continue</p>
        <hr>
        <div class="form-group">
          <label for="email">Email Address</label>
          <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" />
        </div>
        <button type="submit" class="btn btn-primary btn-block mb-3">Login</button>
        <hr>
        <p class="text-center">New user? <a href="/sign-up">Sign up</a></p>
        <p class="text-center">Dont want to create account? <a href="/guest">Continue as guest</a></p>
      </form>
    </div>
  </div>
</div>
{% endblock %}

music-managment/website/templates/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
<div class="container">
    {% if not user.is_artist %}
    <h1>User Details</h1>
    <p><strong>Name:</strong> {{ user.name }}</p>
    <p><strong>Date of Birth:</strong> {{ user.date_of_birth }}</p>
    {% else %}
    <h1>Artist Details</h1>
    <p><strong>Name:</strong> {{ user.name }}</p>
    <p><strong>Date of Birth:</strong> {{ user.date_of_birth }}</p>
    {% endif %}
    <br>
    <hr>
    <br>
    <div class="row">
        <!-- Left column for artist's songs -->
        <div class="col-lg-6">
            <!-- Manage artist profile -->
            {% if user.is_artist %}
            {% if user.songs %}
            <h1>My Songs</h1>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Release Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for song in user.songs %}
                    <tr>
                        <td>{{ song.title }}</td>
                        <td>{{ song.release_date }}</td>
                        <td>
                            <button type="button" class="btn btn-danger" onClick="confirmDelete('{{ song.id }}')">
                                Delete song
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p class="center">You have no songs added. Fill the form to add new songs.</p>
            {% endif %}
            {% endif %}
        </div>

        <!-- Right column for adding new song form -->
        <div class="col-lg-6">
            {% if user.is_artist %}
            <form method="POST">
                <h2>Add a New Song</h2>
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="Enter song title"
                        required />
                </div>
                <div class="form-group">
                    <label for="release_date">Release Date</label>
                    <input type="date" class="form-control" id="release_date" name="release_date" required />
                </div>
                <br />
                <div align="center">
                    <button type="submit" class="btn btn-primary">Add Song</button>
                </div>
            </form>
            {% endif %}
        </div>
    </div>
</div>

<div class="container">
    <h1>Liked Songs</h1>
    {% if liked_songs %}
    <table class="table">
        <thead>
            <tr>
                <th>Song</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for song in songs %}
            {% if song.id in liked_songs %}
            <tr>
                <td>{{ song.title }}</td>
                <td>
                    <button type="button" class="btn btn-danger"
                        onclick="confirmUnlike('{{ song.id }}')"><i class="fa fa-heart"></i></button>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>You have no liked songs</p>
    {% endif %}
</div>

<!-- Confirmation Dialog -->
<dialog id="deleteConfirmation">
    <p>Are you sure you want to delete this song?</p>
    <button id="confirmDeleteButton">Yes</button>
    <button id="cancelDeleteButton">No</button>
</dialog>

<dialog id="unlikeConfirmation">
    <p>Are you sure you want to unlike this song?</p>
    <button id="confirmUnlikeButton">Yes</button>
    <button id="cancelUnlikeButton">No</button>
</dialog>

<script>
    function confirmDelete(songId) {
        const dialog = document.getElementById('deleteConfirmation');
        dialog.showModal();

        const confirmButton = document.getElementById('confirmDeleteButton');
        const cancelButton = document.getElementById('cancelDeleteButton');

        confirmButton.onclick = function () {
            deleteSong(songId);
            dialog.close();
        };

        cancelButton.onclick = function () {
            dialog.close();
        };
    }

    function deleteSong(songId) {
        fetch("/delete-song", {
            method: "POST",
            body: JSON.stringify({ songId: songId }),
        }).then(window.location.href = "/")
    }

    function confirmUnlike(songId) {
        const dialog = document.getElementById('unlikeConfirmation');
        dialog.showModal();

        const confirmButton = document.getElementById('confirmUnlikeButton');
        const cancelButton = document.getElementById('cancelUnlikeButton');

        confirmButton.onclick = function () {
            unlikeSong(songId);
            dialog.close();
        };

        cancelButton.onclick = function () {
            dialog.close();
        };
    }

    function unlikeSong(songId) {
        fetch("/unlike/" + songId, {
            method: "POST",
            body: JSON.stringify({ songId: songId }),
        }).then(window.location.reload());
    }
</script>
{% endblock %}

music-managment/website/templates/search.html
{% extends "base.html" %}
{% block title %}Search{% endblock %}
{% block content %}

<div class="container">
    <h1>Search</h1>
    <form method="POST" action="{{ url_for('auth.search') }}">
        <div class="form-group " >
            <input type="text" class="form-control" id="searchQuery" name="search_query"
                placeholder="Enter song name or artist">
                <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </form>

    <br><br><br>

    {% if search_results %}
    <h2>Search Results:</h2>
    <p>Total results: {{ search_results|length }}</p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Artist</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for song in search_results %}
            <tr>
                <td>{{ song.title }}</td>
                <td>{{ song.artist.name }}</td>
                <td>
                    {% if song.id in liked_songs %}
                    <form action="{{ url_for('views.unlike_song', song_id=song.id) }}" method="post">
                        <button type="submit" class="btn btn-danger"><i class="fa fa-heart"></i></button>
                    </form>
                    {% else %}
                    <form action="{{ url_for('views.like_song', song_id=song.id) }}" method="post">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-heart"></i></button>
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h3 align="center">All Songs</h3>
    <p>Total songs: {{ songs|length }}</p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Release Date</th>
                <th>Artist</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for song in songs %}
            <tr>
                <td>{{ song.title }}</td>
                <td>{{ song.release_date }}</td>
                <td>{{ song.artist.name }}</td>
                <td>
                    {% if song.id in liked_songs %}
                    <form action="{{ url_for('views.unlike_song', song_id=song.id) }}" method="post">
                        <button type="submit" class="btn btn-danger"><i class="fa fa-heart"></i></button>
                    </form>
                    {% else %}
                    <form action="{{ url_for('views.like_song', song_id=song.id) }}" method="post">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-heart"></i></button>
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>

{% endblock %}

music-managment/website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}

<div class="container d-flex justify-content-center align-items-center vh-100">
  <div class="row justify-content-center">
    <div style="min-width: 30em;">
      <form method="POST">
        <h3 class="text-center">Welcome to Mingo Bingo</h3>
        <p class="text-center">Create an account in mingo bingo</p>
        <hr>
        <div class="form-group">
          <label for="email">Email Address</label>
          <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" required />
        </div>
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name" required />
        </div>
        <div class="form-group">
          <label for="dateOfBirth">Date of Birth</label>
          <input type="date" class="form-control" id="dateOfBirth" name="dateOfBirth" required />
        </div>
        <div class="form-group">
          <label for="password1">Password</label>
          <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password" required />
        </div>
        <div class="form-group">
          <label for="confirmPassword">Confirm Password</label>
          <input type="password" class="form-control" id="confirmPassword" name="confirmPassword"
            placeholder="Confirm password" required />
        </div>
        <div class="form-group">
          <label for="isArtist">Are you an artist?</label>
          <select class="form-control" id="isArtist" name="isArtist" required>
            <option value="1">Yes</option>
            <option value="0">No</option>
          </select>
        </div>
        <br />
        <button type="submit" class="btn btn-primary btn-block mb-3">Sign up</button>
        <hr>
        <p class="text-center">Existing user? <a href="/login">Sign in</a></p>
        <p class="text-center">Dont want to create account? <a href="/guest">Continue as guest</a></p>
      </form>
    </div>
  </div>
</div>
{% endblock %}